# Generated by Django 2.1.7 on 2019-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.TextField(max_length=50, verbose_name="Ім'я")),
                ('LName', models.TextField(max_length=50, verbose_name='Прізвище')),
                ('dateOfBirth', models.DateField(verbose_name='Дата народження')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
            },
        ),
    ]
