# Generated by Django 2.1.7 on 2019-04-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Назва')),
                ('Description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('Genre', models.CharField(choices=[('Poetic', 'Поезія'), ('Detective', 'Детектив'), ('Fantasy', 'Фантастика'), ('Computer science', 'Прикладна література'), ('Science', 'Научпоп')], max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Назва')),
                ('Address', models.CharField(max_length=50, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Офіціант',
                'verbose_name_plural': 'Офіціанти',
            },
        ),
        migrations.RenameField(
            model_name='author',
            old_name='dateOfBirth',
            new_name='DateOfBirth',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicationmodels.Place')),
                ('Delivery', models.BooleanField(verbose_name='Доставка')),
                ('RoundTheClock', models.BooleanField(verbose_name='Цілодобово')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Ресторани',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationmodels.Author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='Publications',
            field=models.ManyToManyField(to='applicationmodels.Publication'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationmodels.Restaurant'),
        ),
    ]
