# Generated by Django 2.1.7 on 2019-04-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Людина', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='human',
            name='Language',
            field=models.CharField(choices=[('C#', 'C#'), ('CPP', 'C++'), ('Python', 'DiceUS'), ('JS', 'JavaScript'), ('PHP', 'PHP')], default=('C#', 'C#'), max_length=10),
        ),
    ]
